### ISSUE TITLE
0.0.3 doesn't upload index.html

### ISSUE THREAD

**Issue by kenips** [LevelbossMike/ember-deploy-redis#12] opened 2015-06-03 14:50 UTC
Upgraded to 0.0.3 and start noticing that my `index.html`s are outdated. Turns out that they are completely empty!

```
redis-cli>GET my-ember-app:c2fe6c6
(nil)
```

There's no error message and both upload and activate return success.

Reverting back to 0.0.2 fixes the issue.

**Comment by LevelbossMike** [comment] 2015-06-03 17:06
Hi!

Sorry to hear that.

Most likely caused by https://github.com/LevelbossMike/ember-deploy-redis/pull/9

 This is kind of odd because I tried this out before uploading 0.0.3 to npm and it worked correctly, also tests are green and uploading is tested.

What does your deploy.json look like?

**Comment by LevelbossMike** [comment] 2015-06-03 17:27
does https://github.com/LevelbossMike/ember-deploy-redis/pull/11 fix your issues? If yes this definitely sucks because tests didn't show this. 

I am currently investigating.

**Comment by LevelbossMike** [comment] 2015-06-03 18:02
@kenips this should be fixed on master. I also released version 0.0.4 to npm. I am very sorry that bug snuck in.

Looking into how this remote-redis scenario can be properly tested via travis.

**Closed as completed by LevelbossMike** 2015-06-03 18:02 UTC

**Comment by LevelbossMike** [comment] 2015-06-03 18:10
I have just pulled 0.0.3 from npm. Please use 0.0.4 instead.

**Comment by kenips** [comment] 2015-06-03 20:36
:+1: works. Thanks so much @LevelbossMike!

**Comment by LevelbossMike** [comment] 2015-06-04 07:51
The fix was from @raw1z .Thx again for his PR.
